// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGOFF3TU4C_Iu2WPn5hA38F6xr-P1mwgQ',
    appId: '1:769059591531:web:0a7012d39384f7ebb4682e',
    messagingSenderId: '769059591531',
    projectId: 'iot-home-72f48',
    authDomain: 'iot-home-72f48.firebaseapp.com',
    storageBucket: 'iot-home-72f48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiVQNCXDGFJ6tEEKJ8DvAHxXCG9j1WCRA',
    appId: '1:769059591531:android:e27d3169327547e1b4682e',
    messagingSenderId: '769059591531',
    projectId: 'iot-home-72f48',
    storageBucket: 'iot-home-72f48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaAx7JMMLH8HD8R3nrCSqV0sRZJDZK4NA',
    appId: '1:769059591531:ios:8b1b724363371d82b4682e',
    messagingSenderId: '769059591531',
    projectId: 'iot-home-72f48',
    storageBucket: 'iot-home-72f48.firebasestorage.app',
    iosBundleId: 'com.example.akilliEv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaAx7JMMLH8HD8R3nrCSqV0sRZJDZK4NA',
    appId: '1:769059591531:ios:8b1b724363371d82b4682e',
    messagingSenderId: '769059591531',
    projectId: 'iot-home-72f48',
    storageBucket: 'iot-home-72f48.firebasestorage.app',
    iosBundleId: 'com.example.akilliEv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGOFF3TU4C_Iu2WPn5hA38F6xr-P1mwgQ',
    appId: '1:769059591531:web:9c601042321254b3b4682e',
    messagingSenderId: '769059591531',
    projectId: 'iot-home-72f48',
    authDomain: 'iot-home-72f48.firebaseapp.com',
    storageBucket: 'iot-home-72f48.firebasestorage.app',
  );
}
